M48
; DRILL file {KiCad 7.0.8} date 2023 October 17, Tuesday 13:28:59
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-17T13:28:59-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.7Y-4.4
X5.8Y-4.0
X5.8Y-4.2
X5.8Y-4.4
X6.1Y-3.7
X6.1Y-4.4
X6.4Y-3.7
X6.5Y-4.2
X6.6Y-3.9
X6.7Y-4.4
T2
X6.209Y-3.2496
X6.3074Y-3.2496
T0
M30
